services:
  db:
    image: postgres:16
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-app} 
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../src/db/db-init:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata:
